[Feature/AES-49-new] HorizontalProductDisplayAccordion and FullscreenHeroScroll
aesop/aesop-gel pull request #153
Opened 2020-09-03 06:21 UTC by SamMorgan

2020-09-04 04:41 UTC, zack76 requested changes

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './as sets/images/HorizontalProductDisplayAccordion/candles-product.png',
url is broken

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './assets/images/HorizontalProductDisplayAccordion/Ptolemy-front.png',
cannot find these image files

2020-09-04 04:41 UTC, zack76 commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
could you please remove the event listener in the callback of useEffect

2020-09-04 04:41 UTC, zack76 commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // return (
please delete the unused code

2020-09-04 04:41 UTC, zack76 commented on src/components/FullWidthHeroScroll/components/FullscreenHeroContent/FullscreenHeroContent.module.css
> +  /* @media (--viewport-lg) {
please delete unused code, thanks

2020-09-04 04:41 UTC, zack76 commented on src/components/FullWidthHeroScroll/components/FullscreenHeroContent/FullscreenHeroContent.module.css
> +    /* padding-top: var(--layout-logo-vertical-offset-lg);
please delete unused code, thanks

2020-09-04 04:41 UTC, zack76 commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    window.addEventListener('resize', () => {
remove event listener in the callback

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +        console.log('reset');
please delete the log

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +  window.addEventListener('resize', () => {
remove the event listener

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.js
> +                  cartAction: 'Add to your cart',
i reckon these label or text will be passed as props, it might be better to put in fixture

2020-09-04 04:41 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    let vp = getViewportForWidth(window.innerWidth);
i thought the current `Image` component should've already handled this function. Please double check. also check with `Video` component

2020-09-04 05:49 UTC, zack76 commented on src/components/FullWidthHeroScroll/components/Media/Media.js
> +import React from 'react';
this file also looks like `src/components/MediaWithContent/components/Media/Media.js`

2020-09-04 06:11 UTC, kevin-ho87 commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +export default AccordionProductBackgroundVideo;
There is a gel Video component that handles the 3 video sources. I wonder if that can be used
https://aesop.github.io/aesop-gel/?path=/story/components-video--base-component

2020-09-04 06:36 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
I thought this was correct because it needs, to be triggered on scroll and on render? Sorry if I'm missing something here. What do you suggest?

2020-09-04 06:37 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    window.addEventListener('resize', () => {
Same issue as the scroll event, open to suggestions

2020-09-04 06:37 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/Media/Media.js
> +import React from 'react';
Removed

2020-09-04 06:37 UTC, zack76 commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
just also need to remove it when the component will unmount

2020-09-04 06:39 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +export default AccordionProductBackgroundVideo;
On resize/render it detects the appropriate source file and updates the video element. Does that suffice?

2020-09-04 06:40 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +export default FullscreenVideo;
Needed to make one that would cover the space

2020-09-04 06:45 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            >
This is for the closed accordion items, so you can click on the closed accordions as well as clicking the button. As it was more a feature I didn't think it was necessary for the additional close button. For accessibility could possibly have a hidden button or maybe a conditionally rendered one, if necessary?

2020-09-04 07:02 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            >
Updated. Also changed the class name to just scrollIndictor

2020-09-04 07:28 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
Umm... Cant get this to work properly the way you want

2020-09-04 07:29 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +  window.addEventListener('resize', () => {
What else do you suggest here? the accordions need to be reset when they stack for mobile

2020-09-05 21:39 UTC, beau-charman requested changes

2020-09-08 02:53 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // )
Removed

2020-09-08 02:54 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
Updated with removeEventListener

2020-09-08 02:56 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            >
Updated to a button element

2020-09-08 02:56 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +              }
removed

2020-09-08 02:56 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.stories.mdx
> +import FullWidthHeroScrollFixture from './FullWidthHeroScroll.fixture';
removed unused

2020-09-08 02:56 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +import Hyperlink from '~/components/Hyperlink';
Updated

2020-09-08 02:57 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    let vp = getViewportForWidth(window.innerWidth);
Updated var name

2020-09-08 03:09 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    });
Updated to onClick handler scrollDown

2020-09-08 03:19 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +                <h3
@SamMorgan https://aesop.github.io/aesop-gel/?path=/docs/components-bodycopy--base-component
Please refer to this link for the reference

2020-09-08 03:25 UTC, andrwchang requested changes

2020-09-08 03:25 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +
Please remove commented out codes

2020-09-08 03:25 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +                <h3
@SamMorgan  https://aesop.github.io/aesop-gel/?path=/docs/components-bodycopy--base-component
Please refer to this link for the reference

2020-09-08 03:32 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './as sets/images/HorizontalProductDisplayAccordion/candles-product.png',
Updated

2020-09-08 03:33 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './assets/images/HorizontalProductDisplayAccordion/Ptolemy-front.png',
Added the images, should be fine now

2020-09-08 03:35 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    window.addEventListener('scroll', fadeScrollBtn);
Put the removeEventListener in when unmounted. I think this is correct now let me know if otherwise

2020-09-08 03:35 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // return (
Removed

2020-09-08 03:36 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenHeroContent/FullscreenHeroContent.module.css
> +  /* @media (--viewport-lg) {
removed

2020-09-08 03:57 UTC, kevin-ho87 commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    fadeScrollBtn;
Is there a reason to have this variable here?

2020-09-08 03:59 UTC, kevin-ho87 commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +export default FullscreenVideo;
Maybe you could pass a className into the video component and control from there

2020-09-08 05:17 UTC, andrwchang requested changes

2020-09-08 05:19 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './as sets/images/HorizontalProductDisplayAccordion/candles-product.png',
@zack76 Can you please review?

2020-09-08 05:20 UTC, andrwchang commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    window.addEventListener('resize', () => {
@zack76 can you please review?

2020-09-08 05:20 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +        console.log('reset');
Marked as done from @SamMorgan. @zack76 can you please review?

2020-09-08 05:20 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +  window.addEventListener('resize', () => {
@zack76 review and resolve thanks

2020-09-08 05:21 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProduct/AccordionProduct.js
> +                  cartAction: 'Add to your cart',
@zack76 review and resolve please

2020-09-08 05:21 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    let vp = getViewportForWidth(window.innerWidth);
This needs to be replaced with the Image Block Gel Component

2020-09-08 05:22 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // )
@kevin-ho87 please review and resolve the conversation

2020-09-08 05:22 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            >
@kevin-ho87 please review and resolve the conversation

2020-09-08 05:22 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +              }
@kevin-ho87 please review and resolve the conversation

2020-09-08 05:23 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +import Hyperlink from '~/components/Hyperlink';
@beau-charman please review and resolve the conversation

2020-09-08 05:23 UTC, andrwchang commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +                className="Icon ScrollIndicator-icon"
fixed by @SamMorgan. @beau-charman  Can you please review and close the conversation? Thank you

2020-09-08 05:24 UTC, andrwchang commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    let vp = getViewportForWidth(window.innerWidth);
This needs to be deleted and use the video gel block component @SamMorgan

2020-09-08 05:46 UTC, zack76 commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.fixture.js
> +            './assets/images/HorizontalProductDisplayAccordion/Ptolemy-front.png',
solved

2020-09-08 05:50 UTC, zack76 commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // )
@SamMorgan FYI - https://aesop.github.io/aesop-gel/?path=/story/components-image--base-component

2020-09-08 05:52 UTC, zack76 requested changes
Could you replace `AccordionProductBackgroundImage` and `AccordionProductBackgroundVideo` with `Image` and `Video` in gel componet if possible

2020-09-08 06:07 UTC, beau-charman requested changes
Awesome stuff @SamMorgan , just a few things to clean up

2020-09-08 06:07 UTC, beau-charman commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +      <div className={cx(styles.imgdiv)} data-imgdiv={true} />
could we make this `imageContainer` in case the html element ever needs to change

2020-09-08 06:07 UTC, beau-charman commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    <div className={cx(styles.prodAccBgimg)} ref={BgImgWrap}>
could we change this classname to `productAccordionBigImage`, or even just `bigImage`, as css modules will parse it to ~ `.AccordionProductBackgroundImage__bigImage`

2020-09-08 06:07 UTC, beau-charman commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +    let vp = getViewportForWidth(window.innerWidth);
I am assuming `vp` is `viewport`, so could we change it to that?

2020-09-08 06:07 UTC, beau-charman commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +      className={cx(styles.accordionProductBackgroundVideo)}
If this classname references the top level of the component, can we make it `.base`?

2020-09-08 06:51 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    let vp = getViewportForWidth(window.innerWidth);
This component has been removed so this should be resolved

2020-09-08 06:52 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +            // )
@zack76 substituted for the gel Image component

2020-09-08 06:54 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +export default FullscreenVideo;
@beau-charman Removed these components for the Gel Image & Video

2020-09-08 06:54 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +                <h3
@andrwchang Replaced with BodyCopy component

2020-09-08 06:55 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/components/FullscreenVideo/FullscreenVideo.js
> +    let vp = getViewportForWidth(window.innerWidth);
@andrwchang removed this component

2020-09-08 07:30 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +              <svg viewBox="0 0 50 50">
@beau-charman this is ready for review now

2020-09-08 07:31 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.module.css
> +.ScrollIndicator {
This update has been made

2020-09-08 07:32 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    return () => {
This component has been removed

2020-09-08 07:32 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +      <div className={cx(styles.imgdiv)} data-imgdiv={true} />
This component has been removed

2020-09-08 07:33 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundImage/AccordionProductBackgroundImage.js
> +    <div className={cx(styles.prodAccBgimg)} ref={BgImgWrap}>
This component has been removed

2020-09-08 07:33 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +      className={cx(styles.accordionProductBackgroundVideo)}
This component has been removed

2020-09-08 07:33 UTC, SamMorgan commented on src/components/HorizontalProductDisplayAccordion/components/AccordionProductBackgroundVideo/AccordionProductBackgroundVideo.js
> +    let vp = getViewportForWidth(window.innerWidth);
This component has been removed

2020-09-08 07:36 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +          {textBlocks.map(({ hasSerifFont, text }, index) => {
@beau-charman updated

2020-09-08 07:36 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +              onClick={scrollDown}
This update has been done

2020-09-08 07:37 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    return () => {
Updated

2020-09-09 00:46 UTC, SamMorgan commented on src/components/FullWidthHeroScroll/FullWidthHeroScroll.js
> +    fadeScrollBtn;
Removed extra fadeScrollBtn

2020-09-09 00:58 UTC, andrwchang commented on src/components/HorizontalProductDisplayAccordion/HorizontalProductDisplayAccordion.js
> +      accordionProducts.map((product, i) => {
@SamMorgan Can you please take a look into this?

2020-09-09 07:35 UTC, andrwchang approved these changes
Approved from my end. Hopefully we will get one more approval and should be good to merge

2020-09-10 03:15 UTC, beau-charman commented
to fix up dist/index.js, rebase from develop and rebuild the folder. in future, you shouldnt need to build a dist, and if you do just disregard changes on the dist folder.

2020-09-10 06:13 UTC, merged