[Feature][Feature/AES-1874]: TextInput Component for Footer
aesop/aesop-gel pull request #165
Opened 2020-09-09 03:00 UTC by zack76

TextInput for further use in NewsLetterSignUp component
https://aesoponline.atlassian.net/browse/AES-1874

![Screen Recording 2020-09-09 at 12 52 16 pm](https://user-images.githubusercontent.com/51350376/92548941-91e86280-f29b-11ea-9163-4a6785caf007.gif)

2020-09-10 23:37 UTC, MkMan commented on src/components/Footer/CheckBox/CheckBox.js
> +    <label className={baseClassSet}>
Should we specify the `for` attribute here for accessibility and UX?
https://stackoverflow.com/a/698017/8459521

2020-09-10 23:37 UTC, MkMan commented on src/components/Footer/CheckBox/CheckBox.module.css
> +  -webkit-appearance: none;
Ah... The joys of custom form inputs :smile:

2020-09-10 23:37 UTC, MkMan commented on src/components/Footer/CheckBox/CheckBox.module.css
> +    outline: none !important;
Just confirming the `!important` needed?

2020-09-11 00:11 UTC, zack76 commented on src/components/Footer/CheckBox/CheckBox.js
> +    <label className={baseClassSet}>
updated, also found that react is using `htmlFor` for `for` attribute

2020-09-11 00:11 UTC, zack76 commented on src/components/Footer/CheckBox/CheckBox.module.css
> +    outline: none !important;
updated, thanks so much

2020-09-11 03:40 UTC, hassanraza0054 commented on src/components/Footer/TextInput/TextInput.js
> +          defaultValue={defaultValue}
Based on our discussion, adding this input (pun intended) in. Might be worthwhile to add the autoFocus property as is in web-ui, just in case in a future requirement, if we need input to have the property available, we'll have the skeleton in gel set! 

![image](https://user-images.githubusercontent.com/42990483/92853229-f4279b80-f432-11ea-898c-fb136c512797.png)

2020-09-11 03:52 UTC, MkMan commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
Is `name` used on another element in this component?

2020-09-11 03:54 UTC, zack76 commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
i assume they are using the same value

2020-09-11 03:57 UTC, MkMan commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
I meant should it be assigned to another element to "connect" the label with it? It looks like it's only used on the `label` currently.

2020-09-11 04:19 UTC, hassanraza0054 commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
Do you guys think we need the `htmlFor` property? If i'm not mistaken, this is best used when there is an input field connected. I'm guessing we can go without this given the descendant is a div containing a textArea?

2020-09-11 04:35 UTC, MkMan commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
I think we should keep it, it has accessibility usage. More info [here](https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-explicitly). It also means when you click on the label the form element it's for gets focus which is nice UX. Example [here](https://codepen.io/mkman/pen/OJNZLVY)

@zack76 I think `htmlFor` and `id` should match, based on the link.

2020-09-11 06:02 UTC, zack76 commented on src/components/Footer/TermsBox/TermsBox.js
> +    <label htmlFor={name}>
could you have a look again? appreciate it

2020-09-11 06:10 UTC, MkMan approved these changes

2020-09-11 06:10 UTC, MkMan commented on src/components/Footer/TextInput/TextInput.js
>          <input
Don't forget to add `id` to the input :wink:

2020-09-11 06:19 UTC, zack76 commented on src/components/Footer/TextInput/TextInput.js
>          <input
oh! i added `id` to `CheckBox` and `TermsBox`, but forgot this one. My bad!

2020-09-13 23:05 UTC, hassanraza0054 approved these changes

2020-09-13 23:11 UTC, beau-charman commented
Didn't get a chance to get across this properly one until today. Some good work here @zack76, but we need to pause and take a step back. 

User inputs are going to be a widely shared component, so need to be written in total isolation. 

As GEL is a component library, it does not need to know anything about it's own implementation. The `Footer` component is a red flag in terms of structure. web-ui has a footer, GEL provides abstracted components. we need to provide a `Checkbox` component and web-ui consumes it and applies business logic to it in context (`terms and conditions` for example is a business logic that GEL doesn't need to be worried about)

2020-09-13 23:14 UTC, beau-charman commented
For starters could we change `CheckBox` to `Checkbox`, and `TermsBox` to `Textarea` (as they are React components of HTML elements of the same name)

2020-09-14 01:22 UTC, zack76 commented
> For starters could we change `CheckBox` to `Checkbox`, and `TermsBox` to `Textarea` (as they are React components of HTML elements of the same name)

Thank you Beau for reviewing. Both changes are done.

2020-09-15 06:23 UTC, MkMan commented on src/components/Checkbox/Checkbox.js
> +  id: PropTypes.string,
I think it would be good to mark this as `required`. Same for the other new components that use it with `htmlFor`.

2020-09-15 06:23 UTC, MkMan commented on src/components/Textarea/Textarea.css
> +@import 'styles/index';
This file is called `Textarea.css` while other css files were called `TextInput.module.css`. Just confirming this is intentional.

2020-09-15 06:46 UTC, zack76 commented on src/components/Checkbox/Checkbox.js
> +  id: PropTypes.string,
yeah, updated

2020-09-15 06:46 UTC, zack76 commented on src/components/Textarea/Textarea.css
> +@import 'styles/index';
oh, my bad. updated.

2020-09-16 00:32 UTC, beau-charman requested changes

2020-09-16 00:32 UTC, beau-charman commented on src/components/Checkbox/Checkbox.js
> +  disabled,
keep Component prop booleans prefixed with `is` of `for` and as a positive as it's initial state. Makes it super easy to ready, and comprehend. Especially with `!` bangs. 

For example, here we should have isEnabled. 

Obviously keep the html attribute `disabled` on the `input `

2020-09-16 00:32 UTC, beau-charman commented on src/components/Checkbox/Checkbox.module.css
> +    content: '\2713';
Maybe leave a comment here to what the glyph is?

2020-09-16 00:32 UTC, beau-charman commented on src/components/Checkbox/Checkbox.spec.js
> +  });
We definitely need more tests, but maybe in another piece of work, as user inputs definitely need lots of unit tests

2020-09-16 00:32 UTC, beau-charman commented on src/components/TextInput/TextInput.js
> +  disabled,
same here with `isEnabled`

2020-09-16 00:32 UTC, beau-charman commented on src/components/TextInput/TextInput.js
> +  novalidate,
and here for the boolean, we could simply make it `hasValidation` :  noValidate={!hasValidation}

2020-09-16 00:32 UTC, beau-charman commented on src/components/Textarea/Textarea.js
> +  disabled,
`isEnabled`

2020-09-16 00:32 UTC, beau-charman commented on src/components/Textarea/Textarea.js
> +  const termBoxClassSet = cx(styles.term, styles[theme], termBoxClassName);
`textareaClassSet`

2020-09-16 00:47 UTC, zack76 commented on src/components/Checkbox/Checkbox.js
> +  disabled,
updated

2020-09-16 00:47 UTC, zack76 commented on src/components/Checkbox/Checkbox.module.css
> +    content: '\2713';
updated

2020-09-16 00:47 UTC, zack76 commented on src/components/TextInput/TextInput.js
> +  disabled,
updated

2020-09-16 00:48 UTC, zack76 commented on src/components/TextInput/TextInput.js
> +  novalidate,
updated

2020-09-16 00:48 UTC, zack76 commented on src/components/Textarea/Textarea.js
> +  disabled,
updated

2020-09-16 00:48 UTC, zack76 commented on src/components/Textarea/Textarea.js
> +  const termBoxClassSet = cx(styles.term, styles[theme], termBoxClassName);
updated

2020-09-16 00:49 UTC, zack76 commented on src/components/Checkbox/Checkbox.spec.js
> +  });
will pick it up later

2020-09-17 03:01 UTC, beau-charman approved these changes
nice stuff!

2020-09-17 03:29 UTC, merged