[Feature][AES-1511] Create Product Extract Component for How to Use section
aesop/aesop-gel pull request #166
Opened 2020-09-09 08:56 UTC by hassanraza0054

Add Product Extract component for combination with how to use section

1. Product name is a link to its page and gets underlined on hover
2. Product image to the right
3. Header component used for "Works well with"
4. All area starting from the Header down is clickable space for the product link

Add DefinitionListWithProductExtractComponent

1. Showcases current use case for this component
2. Based on requirements, only one product extract at the end of each definition list

**ProductExtract Component Images**

<img width="1542" alt="Screen Shot 2020-09-09 at 6 47 57 pm" src="https://user-images.githubusercontent.com/42990483/92577255-cc6af300-f2cd-11ea-80cd-170c1e8214dd.png">

<img width="1546" alt="Screen Shot 2020-09-09 at 6 48 35 pm" src="https://user-images.githubusercontent.com/42990483/92577265-cffe7a00-f2cd-11ea-86cc-68f96729bd1b.png">

<img width="1525" alt="Screen Shot 2020-09-09 at 6 49 07 pm" src="https://user-images.githubusercontent.com/42990483/92577268-d0971080-f2cd-11ea-863c-919f0f7f1835.png">

<img width="1524" alt="Screen Shot 2020-09-09 at 6 49 35 pm" src="https://user-images.githubusercontent.com/42990483/92577274-d12fa700-f2cd-11ea-87b3-a9ebfe4a1b59.png">

<img width="1537" alt="Screen Shot 2020-09-09 at 6 49 44 pm" src="https://user-images.githubusercontent.com/42990483/92577278-d260d400-f2cd-11ea-9ba2-51241c497e1e.png">

<img width="1526" alt="Screen Shot 2020-09-09 at 6 49 54 pm" src="https://user-images.githubusercontent.com/42990483/92577279-d2f96a80-f2cd-11ea-88b5-d1082ca96a9c.png">

<img width="1527" alt="Screen Shot 2020-09-09 at 6 50 10 pm" src="https://user-images.githubusercontent.com/42990483/92577286-d42a9780-f2cd-11ea-9467-b1d2791048bb.png">

**DefinitionListWithProductExtract Component Images**

<img width="1543" alt="Screen Shot 2020-09-09 at 6 52 00 pm" src="https://user-images.githubusercontent.com/42990483/92577505-0e943480-f2ce-11ea-9cea-10c9adf2b728.png">

<img width="1546" alt="Screen Shot 2020-09-09 at 6 52 25 pm" src="https://user-images.githubusercontent.com/42990483/92577523-1227bb80-f2ce-11ea-9d2b-51efd7c98521.png">

<img width="1544" alt="Screen Shot 2020-09-09 at 6 52 35 pm" src="https://user-images.githubusercontent.com/42990483/92577528-1358e880-f2ce-11ea-8075-9473f6b3aa3c.png">

<img width="1542" alt="Screen Shot 2020-09-09 at 6 52 49 pm" src="https://user-images.githubusercontent.com/42990483/92577533-13f17f00-f2ce-11ea-9cf0-9127485fd702.png">

2020-09-09 10:06 UTC, zack76 reviewed
Looks good, just a few things need to confirm with you

2020-09-09 11:05 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +    dataTestRef,
Thanks for that! Fixed

2020-09-09 11:06 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  items: [{}],
You're right. Empty array works fine too. Fixed

2020-09-09 11:06 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +    itemNum,
Done

2020-09-09 11:06 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  productBottomBorder: PropTypes.bool,
Done

2020-09-09 11:06 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  itemBottomBorder,
Done

2020-09-09 12:15 UTC, zack76 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +      <ProductExtract
wish to double check if there could be only one product be passed in?

2020-09-09 22:58 UTC, zack76 approved these changes

2020-09-09 23:25 UTC, kevin-ho87 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  },
Is `name` and `url` defaultProps required in this product object?

2020-09-09 23:30 UTC, kevin-ho87 commented on src/components/ProductExtract/ProductExtract.module.css
> +  }
Just a thought. Would this be cleaner to have it in a loop?

2020-09-09 23:33 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  },
I thought url as default was needed but not name for default prop. Could be wrong though

2020-09-09 23:39 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.module.css
> +  }
Probably? But i'm keeping the syntax used consistent with the definition list which also has it written in the same style.

2020-09-09 23:43 UTC, kevin-ho87 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  },
maybe add `prop: undefined`. Just like the other props. Not sure if it makes any difference :P

2020-09-09 23:44 UTC, kevin-ho87 approved these changes

2020-09-10 00:25 UTC, beau-charman requested changes
Dude, this is great, please review comments

2020-09-10 00:25 UTC, beau-charman commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +      url: '/',
I would not pass in a default URL here, either dont render a link, or dont wrap the element in an a tag if there is no URL passed. You can use https://aesop.github.io/aesop-gel/?path=/docs/components-conditionalwrapper--base-component to do so, so in ProductExtract you could do: 

```
<ConditionalWrapper condition={product.url} wrapper={children => (
  <Hyperlink
    className={linkClassSet}
    dataTestRef={dataTestRef}
    title={product.name}
    url={product.url}
  >
    {children}
  </Hyperlink>
))}>
  <>
    <Heading
      className={headingClassSet}
      level={HEADING.LEVEL.FOUR}
      size={HEADING.SIZE.X_X_SMALL}
    >
      <span>{works}</span>
    </Heading>
    <div className={productNameClassSet}>
      <div>
        <span>{product.name}</span>
      </div>
    </div>
    <div className={productImageClassSet}>
      <Image
        altText={product.image.altText}
        small={product.image.small}
      />
    </div>
  <>
</ConditionalWrapper>   
```

2020-09-10 00:25 UTC, beau-charman commented on src/components/ProductExtract/ProductExtract.js
> +import { Heading, Hyperlink } from '~/components';
nice 👍  I am glad the named exports are being used from components/index.js. I need to go back through and changed the other components, I just think its nicer than a seperate import for every component

2020-09-10 00:25 UTC, beau-charman commented on src/components/ProductExtract/ProductExtract.js
> +import React, { forwardRef, Fragment } from 'react';
Could you please order as follows: 

```
import React, { forwardRef, Fragment } from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { HEADING } from '~/constants';
import { Heading, Hyperlink, Image } from '~/components';
import styles from './ProductExtract.module.css';
```

2020-09-10 00:25 UTC, beau-charman commented on src/components/ProductExtract/ProductExtract.js
> +  const isEmptyObject = value => {
could we either use lodash's version of this, or make it a shared 'util'?

2020-09-10 00:25 UTC, beau-charman commented on src/components/ProductExtract/ProductExtract.js
> +    url: '/',
Same here with the default url

2020-09-10 00:25 UTC, beau-charman commented on src/components/ProductExtract/ProductExtract.module.css
> +  @media (--viewport-md) {
Can we please have new lines before nested rules, like line 20, makes things easier to read :)

2020-09-10 01:52 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.module.css
> +  @media (--viewport-md) {
Done! Sorry about that Beau and thanks a ton for the time and attention to detail.

2020-09-10 01:52 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +    url: '/',
Done!

2020-09-10 01:52 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +  const isEmptyObject = value => {
Switched to Lodash's version and works. Done!

2020-09-10 01:54 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +import React, { forwardRef, Fragment } from 'react';
Ordered accordingly. Added the Lodash import before **cx** using the `UserSession.js` component as reference.

![image](https://user-images.githubusercontent.com/42990483/92672564-4e096200-f35c-11ea-8bb3-f1a6e424b345.png)

2020-09-10 01:54 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +      url: '/',
Done! Thanks Beau

2020-09-10 01:57 UTC, beau-charman approved these changes
🙌

2020-09-10 02:05 UTC, merged

2020-09-10 02:08 UTC, hassanraza0054 commented on src/components/DefinitionListWithProductExtract/DefinitionListWithProductExtract.js
> +  },
All good! Stuck with removing url for this one and keeping the rest as is. Thanks for the input Kev!