[Feature][Feature/AES-1786 ] Notification Modal
aesop/aesop-gel pull request #184
Opened 2020-09-14 05:01 UTC by zack76

https://aesoponline.atlassian.net/browse/AES-1876

New components: Notification Modal & Context for Notification for further use in NewsLetterSignUp component

The notification modal will cover the whole footer while will be triggered by only the email subscription button which is the child component of the footer.

![ezgif-6-3a682a818a0c](https://user-images.githubusercontent.com/51350376/93045630-f724c500-f69a-11ea-8f3d-1b851d97340e.gif)

2020-09-17 23:48 UTC, beau-charman requested changes

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/NotificationModal.js
> +import { useNotificationContext } from 'contexts';
```
import React from 'react';
import PropTypes from 'prop-types';
import cx from 'classnames';
import { useNotificationContext } from 'contexts';
import Icon from '~/components/Icon';
import styles from './NotificationModal.module.css';
```

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage,
```  
  backgroundColor,  
  className,
  notificationMessage,
```

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/NotificationModal.js
> +  const onClick = e => {
when defining a event handler, prefix with `handle`, so `handleOnClick `

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage: PropTypes.string,
```
  backgroundColor: PropTypes.string,
  className: PropTypes.string,
  notificationMessage: PropTypes.string,
```

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage: undefined,
```
  backgroundColor: undefined,
  className: undefined,
  notificationMessage: undefined,
```

2020-09-17 23:48 UTC, beau-charman commented on src/components/NotificationModal/ToogleButton.js
> +import React from 'react';
any child components for a parent component, please place them within a subsequent `components` folder. See `Carousel`

2020-09-17 23:48 UTC, beau-charman commented on src/styles/variables/layout.css
> +  --site-sm-margin: 20px;
could we keep the `layout` prefix here? Makes it easy to know where the variable is kept. 

```
  --layout-lg-margin: 40px;
  --layout-md-margin: 34px;
  --layout-sm-margin: 20px;
```

2020-09-17 23:48 UTC, beau-charman commented
Nice stuff @zack76. Just a couple of things to address.

2020-09-18 02:31 UTC, zack76 commented on src/components/NotificationModal/NotificationModal.js
> +import { useNotificationContext } from 'contexts';
updated

2020-09-18 02:31 UTC, zack76 commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage,
updated

2020-09-18 02:31 UTC, zack76 commented on src/components/NotificationModal/NotificationModal.js
> +  const onClick = e => {
updated

2020-09-18 02:31 UTC, zack76 commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage: PropTypes.string,
updated

2020-09-18 02:32 UTC, zack76 commented on src/components/NotificationModal/NotificationModal.js
> +  notificationMessage: undefined,
updated

2020-09-18 02:32 UTC, zack76 commented on src/styles/variables/layout.css
> +  --site-sm-margin: 20px;
updated

2020-09-18 02:33 UTC, zack76 commented on src/components/NotificationModal/ToogleButton.js
> +import React from 'react';
updated

2020-09-18 02:33 UTC, beau-charman approved these changes
you boss Zack!

2020-09-18 02:35 UTC, merged