Feature/aes 1505 double media video scroll
aesop/aesop-gel pull request #188
Opened 2020-09-15 03:49 UTC by MkMan

This is to allow Videos to play as the user scrolls down the page 🤷 

Also adds some tips in the README.md to make development easier

2020-09-17 07:03 UTC, kevin-ho87 commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Does storybook still display the proptypes if its stored in a variable?

2020-09-17 22:21 UTC, MkMan commented on README.md
> +npm run build:watch
No, this is here in Gel. I added a new npm script called `build:watch` that will produce a prod-like compilation every time you change code. 

What I have been doing is: use `npm link` to link Web UI to the local Gel, and then run `build:watch` and `build-watch`. Then every time I made code changes in Gel or Web UI the changes are detected on either side and are there when I refresh the browser.

2020-09-17 22:27 UTC, MkMan commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Do you mean the `API` list under the `Docs` tab? I am not sure how that's generated, some components have it and others don't.

I can change this back but I feel like it shouldn't be an issue, SB should be able to do a simple variable evaluation.

2020-09-17 23:29 UTC, kevin-ho87 commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Maybe do a quick check, from my experience it didn't compile when the proptypes were stored in a variable.

2020-09-17 23:48 UTC, MkMan commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Story book loads fine. Is this what you meant?

![image](https://user-images.githubusercontent.com/33766083/93539410-102bbf80-f994-11ea-816b-c9813df6cdfd.png)

2020-09-17 23:56 UTC, kevin-ho87 commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Oh, sorry I meant to say proptypes displaying in the `Docs` tab

2020-09-17 23:59 UTC, beau-charman requested changes

2020-09-17 23:59 UTC, beau-charman commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Kevin is referring to the `Docs` tab

2020-09-17 23:59 UTC, beau-charman commented on src/components/Video/Video.js
> +    return function cleanUp() {
`cleanup` is correct in this context. 

> When you need a term meaning (1) to make clean or orderly, or (2) to make oneself clean, use clean up—two words. In American and Canadian English, the one-word cleanup is a noun referring to (1) a thorough cleaning or (2) the act or process of cleaning. It may also function as an adjective in phrases like cleanup crew and cleanup hitter. British writers typically use the hyphenated form—clean-up—instead. Australian and New Zealand publications are inconsistent on the matter.

2020-09-17 23:59 UTC, beau-charman commented on src/components/Video/Video.js
> +    return function cleanUp() {
`cleanUp` camel-cased from clean up would be the action, verb to clean. This `cleanup` function however is the umbrella noun / title for multiple clean up actions.

2020-09-18 00:04 UTC, MkMan commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
Yeah the Docs -> API section is empty but that's the same as `develop`. Anyway, I'll change it to be hardcoded.

![image](https://user-images.githubusercontent.com/33766083/93540204-4c601f80-f996-11ea-9a6a-f96e75725b60.png)

2020-09-18 00:12 UTC, MkMan commented on src/components/Video/Video.js
> +    return function cleanUp() {
Reverted

2020-09-18 02:35 UTC, beau-charman commented on src/components/DoubleMedia/DoubleMedia.js
> +    type: mediaType,
bigger issue there 😢

2020-09-18 02:35 UTC, beau-charman approved these changes

2020-09-18 03:15 UTC, merged