[Feature][Feature/AES-1878]: FooterBlock Component for New Footer
aesop/aesop-gel pull request #192
Opened 2020-09-16 05:28 UTC by zack76

https://aesoponline.atlassian.net/browse/AES-1523

2020-09-17 07:23 UTC, kevin-ho87 requested changes

2020-09-17 07:23 UTC, kevin-ho87 commented on src/components/FooterBlock/FooterBlock.js
> +      <div className={titleClassSet}>{title}</div>
Are you able to use a heading eg: `<h5 />` for the title/heading. For html semantics/accessibility.

2020-09-17 07:23 UTC, kevin-ho87 commented on src/components/FooterBlock/FooterBlock.js
> +    links && !isVisibleOnTabletAndMobile && styles.invisible,
I was wondering if you could use the `<Hidden />` component to control the display logic. Just a thought.

2020-09-17 07:23 UTC, kevin-ho87 commented on src/components/FooterBlock/FooterBlock.js
> +        ))}
Are you able to update this to a list structure `ul > li* > a` from html accessibility.

2020-09-17 07:23 UTC, kevin-ho87 commented on src/components/FooterBlock/FooterBlock.js
> +  title: PropTypes.string,
Could you change `title` to `heading`. Just that `title` is a reserve html keyword.

2020-09-18 00:20 UTC, beau-charman commented on src/components/FooterBlock/FooterBlock.js
> +      <div className={titleClassSet}>{title}</div>
<Heading level="5" />

2020-09-18 00:21 UTC, beau-charman commented on src/components/FooterBlock/FooterBlock.js
> +  title: PropTypes.string,
Thank you @kevin-ho87!

2020-09-18 00:24 UTC, beau-charman approved these changes

2020-09-18 00:24 UTC, beau-charman commented
Just a few things to address

2020-09-18 01:24 UTC, zack76 commented on src/components/FooterBlock/FooterBlock.js
> +      <div className={titleClassSet}>{title}</div>
updated

2020-09-18 01:25 UTC, zack76 commented on src/components/FooterBlock/FooterBlock.js
> +    links && !isVisibleOnTabletAndMobile && styles.invisible,
updated

2020-09-18 01:25 UTC, zack76 commented on src/components/FooterBlock/FooterBlock.js
> +        ))}
updated

2020-09-18 01:25 UTC, zack76 commented on src/components/FooterBlock/FooterBlock.js
> +  title: PropTypes.string,
updated

2020-09-18 01:41 UTC, kevin-ho87 approved these changes

2020-09-18 02:04 UTC, merged