[Feature][AES-1511] Create Product Extract Component for How to Use section [Add Flex for image]
aesop/aesop-gel pull request #193
Opened 2020-09-17 06:03 UTC by hassanraza0054

Included Flex logic to make image with dynamic while setting max height to 50px as per requirement.

2020-09-17 06:54 UTC, zack76 requested changes
<img width="953" alt="Screen Shot 2020-09-17 at 4 53 54 pm" src="https://user-images.githubusercontent.com/51350376/93430709-710cb680-f906-11ea-9913-e7c6322e8197.png">
One border is missing, could you double-check with it?

Also the width of this slice looks more than 100%

2020-09-17 07:01 UTC, hassanraza0054 commented
> <img alt="Screen Shot 2020-09-17 at 4 53 54 pm" width="953" src="https://user-images.githubusercontent.com/51350376/93430709-710cb680-f906-11ea-9913-e7c6322e8197.png">
> 
> One border is missing, could you double-check with it?
> Also the width of this slice looks more than 100%

Ah the DefinitionListWithProductExtract file is just a showcase component. If you want to see the borders, just tick the relevant boxes in the knobs! 

Let me have a look at the width issue.

2020-09-17 07:24 UTC, hassanraza0054 commented
Just adding a note that the width seems to be alright from my end. Made another commit to correct fixtures and add image properties as per your suggestion. Thanks @zack76

2020-09-17 23:35 UTC, kevin-ho87 commented on src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
> +      className="test delayAnimation slideIn"
Where is this `test` coming from?

2020-09-17 23:39 UTC, zack76 requested changes

2020-09-17 23:39 UTC, zack76 commented on src/components/ProductExtract/ProductExtract.js
> +  const flexClassSet = cx(styles.test, styles.delayAnimation, {
`test` here? @kevin-ho87 
should be deleted i think @hassanraza0054

2020-09-18 00:27 UTC, beau-charman commented on src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
> +      className="test delayAnimation slideIn"
```
.test {
  display: flex;
  justify-content: space-between;
}
```

2020-09-20 23:04 UTC, hassanraza0054 commented on src/components/ProductExtract/__snapshots__/ProductExtract.spec.js.snap
> +      className="test delayAnimation slideIn"
Change made! Sorry for that and thanks for the catch!

2020-09-20 23:04 UTC, hassanraza0054 commented on src/components/ProductExtract/ProductExtract.js
> +  const flexClassSet = cx(styles.test, styles.delayAnimation, {
Done! Thanks for the catch

2020-09-20 23:29 UTC, zack76 approved these changes

2020-09-20 23:32 UTC, kevin-ho87 approved these changes

2020-09-20 23:35 UTC, merged