[Feature][Feature/AES-1789] IconLink
aesop/aesop-gel pull request #197
Opened 2020-09-18 03:54 UTC by zack76

**New components: Icon Link for further use in Footer component**

![Screen Recording 2020-09-18 at 1 49 08 pm](https://user-images.githubusercontent.com/51350376/93553372-25b1e100-f9b6-11ea-94bc-d1c1e1bf929b.gif)

2020-09-21 00:19 UTC, beau-charman requested changes

2020-09-21 00:19 UTC, beau-charman commented on src/components/IconLink/IconLink.js
> +  openInANewWindow: true,
can we change the prop to `hasTargetInNewWindow` for boolean naming and Hyperlink prop name consistency?

2020-09-21 00:19 UTC, beau-charman commented on src/components/IconLink/IconLink.js
> +        style={{ height: `${height}px`, width: `${width}px` }}
Do these values need to change with media queries?

2020-09-21 04:05 UTC, zack76 commented on src/components/IconLink/IconLink.js
> +  openInANewWindow: true,
updated

2020-09-21 04:05 UTC, zack76 commented on src/components/IconLink/IconLink.js
> +        style={{ height: `${height}px`, width: `${width}px` }}
updated

2020-09-24 00:05 UTC, kevin-ho87 commented
Just a curious question. what happens when different images with different heights are added? how would they line up?

2020-09-25 02:01 UTC, kevin-ho87 approved these changes

2020-09-29 11:52 UTC, merged