Feature/aes 1553 create text over full width slice
aesop/aesop-gel pull request #224
Opened 2020-10-05 22:02 UTC by MkMan

Adding a new Slice for [AES-1553](https://aesoponline.atlassian.net/browse/AES-1553)

![localhost_6006__path=_story_components-textoverfullwidthasset--base-component](https://user-images.githubusercontent.com/33766083/95136846-9af12480-07b2-11eb-846c-d3fb64090293.png)

2020-10-05 22:27 UTC, zack76 commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.module.css
> +    @media (--viewport-lg) {
`Top` and `Bottom` have the same effects in large views. Am I right?

2020-10-05 22:38 UTC, beau-charman requested changes

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +import styles from './TextOverFullWidthAsset.module.css';
can we drop this one to the bottom of the import list?

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +  copyHeight,
```
copyHeight,
copySide,
```

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +      hasPlayInFullScreen: false,
```
hasPlayInFullScreen: false,
hasSpanContent: false,
```

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +      isFullWidth: true,
```
isFullWidth: true,
isHeroFullWidth: false,
```

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.module.css
> +    @media (--viewport-lg) {
yeah, I guess this could be refactored to:

```
&.Bottom {
  @media (--viewport-md) {
    top: auto;
    bottom: 0;
  }

  @media (--viewport-lg) {
    bottom: auto;
  }
}

&.Top,
&.Bottom {
  @media (--viewport-lg) {
    top: 50%;
    transform: translateY(-50%);
  }
}
```

2020-10-05 22:38 UTC, beau-charman commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.spec.js
> +});
So good. Thank you.

2020-10-05 22:42 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.spec.js
> +});
My pleasure :heart:

2020-10-05 23:01 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.module.css
> +    @media (--viewport-lg) {
Originally it was meant to be for tablet only but there has just been a requirement change a few minutes ago to make it on mobile and tablet only. I'll revisit the styles and try to incorporate the suggested change while changing to meet the new requirement.

2020-10-06 01:10 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +import styles from './TextOverFullWidthAsset.module.css';
Done

2020-10-06 01:11 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +  copyHeight,
:+1:

2020-10-06 01:11 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +      hasPlayInFullScreen: false,
:+1:

2020-10-06 01:11 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.js
> +      isFullWidth: true,
:+1:

2020-10-06 01:12 UTC, MkMan commented on src/components/TextOverFullWidthAsset/TextOverFullWidthAsset.module.css
> +    @media (--viewport-lg) {
I have refactored as per @beau-charman's suggestion

2020-10-06 01:13 UTC, beau-charman approved these changes

2020-10-06 21:41 UTC, MkMan commented
Waiting for the slice to pass UI review before merging.

2020-10-07 22:13 UTC, hassanraza0054 approved these changes

2020-10-09 00:31 UTC, merged