feat(hooks): add  useExecuteOnImpression hook
aesop/aesop-gel pull request #241
Opened 2020-10-20 23:06 UTC by MkMan

Adding a hook to execute a function when the element comes into view.

2020-10-20 23:57 UTC, zack76 approved these changes

2020-10-21 00:45 UTC, hassanraza0054 approved these changes

2020-10-21 22:08 UTC, beau-charman requested changes
The only thing I would ask to change is the references to `functionToCall`, `functionToExecute`, etc to `callback` - to communicate what it actually is.

2020-10-21 22:08 UTC, beau-charman commented on src/customHooks/useExecuteOnImpression/useExecuteOnImpression.js
> + * const myFunction = () => console.log('Execute order 66');
😂

2020-10-21 22:08 UTC, beau-charman commented on src/customHooks/useExecuteOnImpression/useExecuteOnImpression.js
> + * const myFunction = () => console.log('Execute order 66');
![tenor](https://user-images.githubusercontent.com/53842852/96792189-9e88da80-1445-11eb-9590-91e0bab991ec.gif)

2020-10-21 22:11 UTC, beau-charman commented
Like the verb `execute` is cool and all, but the use of it makes it seem that it's doing something special within this hook - like a event handler has access to its target. But this just calls a callback function. So calling the argument `callback` will communicate that. I hope that makes sense

2020-10-21 23:05 UTC, beau-charman approved these changes

2020-10-21 23:30 UTC, merged