[Feature/PUR-173-pdpbreadtrack]: PDP breadcrumb track
aesop/aesop-gel pull request #428
Opened 2021-05-04 01:27 UTC by kevin-ho87

**Ticket**
https://aesoponline.atlassian.net/browse/PUR-173

**Description**
Pass callback function to PDP header when a link in breadcrumb is clicked

2021-05-10 00:38 UTC, MkMan approved these changes

2021-05-10 00:46 UTC, beau-charman commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +              onClick={() => onHyperlinkClick(item)}
Can you bump this one out of the render for me? thank you!

Like:

```
const handleOnHyperlinkClick() => onHyperlinkClick(item);
...
onClick={handleOnHyperlinkClick}
```

2021-05-10 00:48 UTC, beau-charman commented on src/components/ProductDetailHeader/ProductDetailHeader.js
> +                onBreadcrumbClick(item, selectedVariant)
Same here for the anonymous function in the render

2021-05-10 00:48 UTC, beau-charman commented on src/components/ProductDetailHeader/ProductDetailHeader.js
> +                onBreadcrumbClick(item, selectedVariant)
And here, thank you! (Same here for the anonymous function in the render)

2021-05-10 00:49 UTC, beau-charman requested changes
Just had a few items around inline anonymous function in the render returns

2021-05-10 01:29 UTC, beau-charman commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +              onClick={() => onHyperlinkClick(item)}
For example, abstract out the `map`'s UI logic. 

```
const ListItem = ({ item }) => {
  const handleOnHyperlinkClick = () => onHyperlinkClick(item);
    
  return (
    <li className={styles.item} >
      <Hyperlink
        className={styles.link}
        id={item.id}
        onClick={handleOnHyperlinkClick}
        theme={theme}
        title={item.title}
        url={item.url}
      >
        {item.label}
      </Hyperlink>
    </li>
  )
}

return (
  <nav className={classSet} data-testid="data-testid-Breadcrumbs">
    <ul className={styles.list}>
      {items.map(item => (
        <ListItem item={item} key={item.id} />
      ))}
    </ul>
  </nav>
);
```

2021-05-10 02:13 UTC, kevin-ho87 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +              onClick={() => onHyperlinkClick(item)}
updated

2021-05-10 02:13 UTC, kevin-ho87 commented on src/components/ProductDetailHeader/ProductDetailHeader.js
> +                onBreadcrumbClick(item, selectedVariant)
updated

2021-05-10 02:13 UTC, kevin-ho87 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +              onClick={() => onHyperlinkClick(item)}
updated

2021-05-11 23:25 UTC, beau-charman approved these changes

2021-05-11 23:28 UTC, merged

2021-05-11 23:29 UTC, zack76 commented
Does it go to develop? @kevin-ho87