[Feature/CON-845 Add back button]
aesop/aesop-gel pull request #596
Opened 2021-10-19 01:45 UTC by cyrusxzw

-- Add 'isOpenSearchBackToMenu' in GlobalNavigation
-- Web-Ui will pass 'isOpenSearchBackToMenu' to 'MobileView.tsx' after clicking back button
-- 'isOpenSearchBackToMenu' is a boolean to control open Menu or not when travelling back from Search and Stores

2021-10-19 02:07 UTC, MkMan commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  }, [isOpenSearchBackToMenu]);
There are a couple of [linting issues](https://github.com/aesop/aesop-gel/runs/3933884891?check_suite_focus=true#step:6:86) with these 2 lines. Should be easy to address 🙂

2021-10-19 02:07 UTC, MkMan commented on src/components/GlobalNavigation/GlobalNavigation.types.ts
> +  isOpenSearchBackToMenu?: boolean;
I don't understand what this variable does from its name. Can you please explain? 
Good boolean naming standards though 👍

2021-10-19 04:26 UTC, cyrusxzw commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +      setActiveCollectionId('top');
I'll disable eslint. Cause every time isOpenSearchBackToMenu change, will result in dispatching setActiveCollectionId.

2021-10-19 04:51 UTC, MkMan commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Nice! The linting warning is gone now 👍 
Could you please include a comment explaining why the rule was disabled? That way future developers know the intention.

```ts
    // eslint-disable-next-line react-hooks/exhaustive-deps -- explanation why the rule is disabled
```

2021-10-19 22:38 UTC, hassanraza0054 approved these changes

2021-10-19 22:41 UTC, hassanraza0054 requested changes

2021-10-19 22:41 UTC, hassanraza0054 commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
Could you actually quickly make this into a custom hook? That way, we stay consistent with the pattern of not just adding a blank useEffect into any of the views.

2021-10-19 22:43 UTC, cyrusxzw commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
Good pick, I'll do it. ✌🏻

2021-10-19 22:45 UTC, MkMan commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
What would the hook do? 🤔

2021-10-19 23:07 UTC, cyrusxzw commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
Do the same as useEffect

2021-10-20 01:11 UTC, MkMan commented on src/customHooks/useOpenMenuFromSearch/useOpenMenuFromSearch.ts
> +const useOpenMenuFromSearch: UseOpenMenuFromSearch= (isOpenSearchBackToMenu, setActiveCollectionId) => {
I don't think that's correct 😅  There are existing [components](https://github.com/aesop/aesop-gel/search?l=TSX&q=useeffect) that use `useEffect` in their body.

If it's a standard in the Navigation to move `useEffect` out of components then I think this should remain within the Navigation folders. It's not reusable outside of the context of Navigation and so shouldn't be a global hook.

2021-10-20 01:14 UTC, cyrusxzw commented on src/customHooks/useOpenMenuFromSearch/useOpenMenuFromSearch.ts
> +const useOpenMenuFromSearch: UseOpenMenuFromSearch= (isOpenSearchBackToMenu, setActiveCollectionId) => {
Yea, I think move it into Navigation folder is better. What do you think @hassanraza0054 ?

2021-10-20 01:35 UTC, hassanraza0054 commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
I personally think it might be good to isolate @MkMan for two reasons:-

1. The hook could potentially be dealing with more variables in the future
2. From a visual consistency point, none of the views have a useEffect inside the nav components directly, but rather are using defined hooks (e.g. useFocusOnFirst) in a separate directory

2021-10-20 01:38 UTC, hassanraza0054 commented on src/customHooks/useOpenMenuFromSearch/useOpenMenuFromSearch.ts
> +const useOpenMenuFromSearch: UseOpenMenuFromSearch= (isOpenSearchBackToMenu, setActiveCollectionId) => {
Actually double minded about that now. If the team thinks we are better off with calling a direct useEffect, lets go with that @cyrusxzw . We can then add the useEffect directly in just mobile view.

2021-10-20 01:47 UTC, MkMan commented on src/components/GlobalNavigation/components/MobileView/MobileView.tsx
> +  useEffect(
In the picture you provided [here](https://github.com/aesop/aesop-gel/pull/596#discussion_r732294712) all these hooks are generic. Any component or even React app (Aesop or otherwise) can use them 🙌 

That's not the case with the functionality we're discussing. It's tightly coupled to Navigation and is not generic or reusable.

If the convention in Navigation is to extract `useEffect` code outside of components, that's ok, but the code should remain close to the component using it because it's coupled to it.

I hope that helps 😃

2021-10-20 02:42 UTC, hassanraza0054 approved these changes

2021-10-20 02:45 UTC, merged